export const dynamic = 'force-dynamic'

import { redirect } from 'next/navigation'
import { createServerSupabaseClient, createSupabaseServerComponentClient } from '@/lib/supabase'
import { ArtifactCard } from '@/components/artifacts/ArtifactCard'
import { Artifact } from '@/types'

export default async function ArtifactsPage() {
  const authClient = await createSupabaseServerComponentClient()
  const { data: { user } } = await authClient.auth.getUser()
  if (!user) redirect('/login')

  const supabase = createServerSupabaseClient()
  const { data } = await supabase
    .from('artifacts')
    .select('*')
    .eq('created_by', user.id)
    .order('created_at', { ascending: false })
    .limit(100)

  const artifacts = (data ?? []).filter((a: any) =>
    !a.body?.startsWith('[TOOL EXECUTION FAILED') &&
    !a.title?.startsWith('[TOOL EXECUTION FAILED')
  ) as Artifact[]

  return (
    <div>
      {/* Header */}
      <div style={{ marginBottom: 28 }}>
        <h1 style={{
          fontFamily: 'var(--font-syne, Syne)',
          fontWeight: 700,
          fontSize: 24,
          color: 'var(--text)',
          marginBottom: 4,
          letterSpacing: '-0.02em',
        }}>
          Company Artifacts
        </h1>
        <p style={{ fontSize: 13, color: 'var(--text-3)', fontFamily: 'Inter, sans-serif' }}>
          {artifacts.length > 0
            ? `${artifacts.length} file${artifacts.length !== 1 ? 's' : ''} — click any row to inspect, or download directly.`
            : 'Permanent work outputs generated by your departments.'
          }
        </p>
      </div>

      {artifacts.length === 0 ? (
        <div style={{
          textAlign: 'center',
          padding: '100px 20px',
          color: 'var(--text-3)',
          fontFamily: 'var(--font-dm-mono, monospace)',
          fontSize: 13,
          background: 'rgba(255,255,255,0.02)',
          borderRadius: 16,
          border: '1px dashed rgba(255,255,255,0.08)',
        }}>
          <svg width="48" height="48" fill="none" stroke="currentColor" strokeWidth="1" viewBox="0 0 24 24"
            style={{ margin: '0 auto 16px', opacity: 0.3 }}>
            <path d="M22 19a2 2 0 01-2 2H4a2 2 0 01-2-2V5a2 2 0 012-2h5l2 3h9a2 2 0 012 2z"/>
          </svg>
          <div style={{ marginBottom: 8 }}>No artifacts generated yet.</div>
          <div style={{ fontSize: 11, opacity: 0.6 }}>
            Approve tasks to see your departments create work files here.
          </div>
        </div>
      ) : (
        <>
          {/* Column Headers */}
          <div style={{
            display: 'grid',
            gridTemplateColumns: '56px 1fr 120px',
            padding: '6px 18px',
            marginBottom: 4,
          }}>
            <div />
            <div style={{
              fontSize: 10,
              fontFamily: 'var(--font-dm-mono, monospace)',
              color: 'var(--text-4)',
              letterSpacing: '0.08em',
              textTransform: 'uppercase',
            }}>
              File
            </div>
            <div style={{
              fontSize: 10,
              fontFamily: 'var(--font-dm-mono, monospace)',
              color: 'var(--text-4)',
              letterSpacing: '0.08em',
              textTransform: 'uppercase',
              textAlign: 'right',
            }}>
              Actions
            </div>
          </div>

          {/* File List */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
            {artifacts.map(artifact => (
              <ArtifactCard key={artifact.id} artifact={artifact} />
            ))}
          </div>
        </>
      )}
    </div>
  )
}
